### ISSUE TITLE
Algumas imagens de deputados não são carregadas

### ISSUE THREAD

**Issue by jeffersonrpn** [italo-batista/vidinha-de-balada#10]
A API retorna _NA_ no campo _urlfoto_

**Comment by leticiawanderley** [comment]
Jeff, coloca um exemplo de deputado ou id de deputado que tá com esse problema, por favor

**Comment by jeffersonrpn** [comment]
Faz uma requisição pra https://vidinha-de-balada.herokuapp.com/top10
Você vai ver que FERNANDO TORRES vem com "urlfoto": "NA"

**Comment by italo-batista** [comment]
Commitei numa branch 'urlfotos'.

**Comment by leticiawanderley** [comment]
O problema era que tava faltando as informações desse FERNANDO TORRES no arquivo busca.csv.
Eu consertei mas tem que fazer deploy no heroku para funcionar, por enquanto é melhor usar a solução de Ítalo.

**Comment by italo-batista** [comment]
Eita! Tu tinha ajeitado já? O deploy no heroku é automático. Se tu fazer merge com master já vai.

**Comment by leticiawanderley** [comment]
Eita, então eu acho que não consertei, naquele link do heroku ainda tá errado.

**Comment by italo-batista** [comment]
Não, acho que não foi isso. O deploy feito com o pr que tu deu agora pro master deu build failed. O build log não ajuda muito:

```
Build timed out while waiting to start.
```

**Comment by leticiawanderley** [comment]
Tem como fazer deploy novamente?

**Comment by italo-batista** [comment]
Eu fiz novamente, manualmente, e deu a mesma coisa. :thinking:

**Comment by leticiawanderley** [comment]
Deu certo o deploy. :top:
