### ISSUE TITLE
Add ao Perfil do Deputado: EMPRESAS PARCEIRAS  (front-end)

### ISSUE THREAD

**Issue by italo-batista** [italo-batista/vidinha-de-balada#16]

**Comment by jeffersonrpn** [comment]
No endpoint empresasParceiras não vem nome nem CNPJ das empresas.

**Comment by italo-batista** [comment]
É porque muitas observações não possuem ou CNPJ ou Nome. Esses dados são bem "..."... Enfim. O que podemos fazer? @michellymenezes
