### ISSUE TITLE
Adicionar filtro por uf e/ou partido no Top10 (backend)

### ISSUE THREAD

**Issue by jeffersonrpn** [italo-batista/vidinha-de-balada#21]
http://vidinhadebalada.com/api/top10/<uf>

**Comment by italo-batista** [comment]
[8879bb5](https://github.com/italo-batista/vidinha-de-balada/commit/8879bb58e66d6526f3306cecac963999f07d54da)

branch vemApi

**/top10**: top 10 geral

**/top10/filter/uf/PB**: top 10 Paraíba

**/top10/filter/partido/PT**: top 10 PT

**Comment by italo-batista** [comment]
Vou mudar isso para:

**/top10**: top 10 geral

**/top10/uf/PB**: top 10 Paraíba

**/top10/partido/PT**: top 10 P
