### ISSUE TITLE
Ordenação do ranking

### ISSUE THREAD

**Issue by jeffersonrpn** [italo-batista/vidinha-de-balada#30]
Ordenar o ranking por valor total gasto e não a razão entre gasto e cota.

**Comment by italo-batista** [comment]
:thinking: 
Não é melhor destacar o coeficiente de rankeamento não?
Porque ordenar o gastômetro com base somente no valor gasto, sem levar em conta a cota mensal...

**Comment by italo-batista** [comment]
Ou deixar no subtítulo ou numa info, não sei: rankeamento baseado em cota mensal e valor gasto.

**Comment by jeffersonrpn** [comment]
É que tem gente que gasta menos e está a cima de quem gasta mais. Pro usuário não dá pra entender pq isso ocorre.

**Comment by italo-batista** [comment]
Sim, eu entendo. Mas é justo comparar dessa forma? A gente discutiu isso... Comparar deputados de estados diferentes.. Por isso que pergunto, não é melhor dizer que o **rankeamento é feito amortizando o valor gasto pela cota mensal**? 

@talitalobo @michellymenezes @arthurlustosa @leticiawanderley @helderronyer

**Comment by michellymenezes** [comment]
Se for pra ordenar pelo coeficiente, tem que deixar bem claro esse valor, de maneira que se veja que o coeficiente de que está no topo é maior do que quem está abaixo. Caso contrário, acho melhor ordenar pelo valor bruto pra n confundir nada. 

Ou podemos seguir a sugestão dada e permitir que o usuário alterne entre os dois tipo de ordenação.

**Comment by jeffersonrpn** [comment]
Vamos fazer isso (combinei com @italo-batista). Terá o ranking geral por valor bruto e pelo coeficiente. No filtro se escolhe qual será.

**Comment by italo-batista** [comment]
Exemplos:

- vidinhadebalada.com/api/top10
- vidinhadebalada.com/api/top10/rankeado
- vidinhadebalada.com/api/top10/partido/PT
- vidinhadebalada.com/api/top10/rankeado/partido/PT
