### ISSUE TITLE
Texto explicativo para os selos

### ISSUE THREAD

**Issue by nazareno** [italo-batista/vidinha-de-balada#35]
Pelo menos explicando qual a condição para o deputado ganhar cada um. Se possível dizendo quando ele ganhou.

**Comment by michellymenezes** [comment]
Tem isso aí quando vc clica em CEAP. 
http://vidinhadebalada.com/#!/ceap

**Comment by nazareno** [comment]
Legal, mas era bom ter o texto na página que tem o selo também. (Não é bug, é um enhancement :))
Outra coisa: o selo de bom e ruim quanto a presenças tem a mesma cor. Seria mais fácil entender com cores diferentes.

**Comment by michellymenezes** [comment]
Acho que isso das cores poderia ser um tom mais claro e outro mais escuro. Assim dá pra associar a cor a categoria e a tonalidade a bom ou ruim.
